import { Router, type IRouter } from "express";
import healthRouter from "./health";
import dashboardRouter from "./dashboard";
import customersRouter from "./customers";
import customersWinbackRouter from "./customers-winback";
import salesRouter from "./sales";
import campaignsRouter from "./campaigns";
import campaignSuggestionsRouter from "./campaign-suggestions";
import loyaltyRouter from "./loyalty";
import postsRouter from "./posts";
import footfallRouter from "./footfall";
import appointmentsRouter from "./appointments";
import staffRouter from "./staff";
import expensesRouter from "./expenses";
import inventoryRouter from "./inventory";
import reviewsRouter from "./reviews";
import referralsRouter from "./referrals";
import invoicesRouter from "./invoices";
import forecastRouter from "./forecast";
import openaiRouter from "./openai";

const router: IRouter = Router();

router.use(healthRouter);
router.use(dashboardRouter);
router.use(customersWinbackRouter);
router.use(customersRouter);
router.use(salesRouter);
router.use(campaignSuggestionsRouter);
router.use(campaignsRouter);
router.use(loyaltyRouter);
router.use(postsRouter);
router.use(footfallRouter);
router.use(appointmentsRouter);
router.use(staffRouter);
router.use(expensesRouter);
router.use(inventoryRouter);
router.use(reviewsRouter);
router.use(referralsRouter);
router.use(invoicesRouter);
router.use(forecastRouter);
router.use(openaiRouter);

export default router;
